
#   Kelsey's Dotfile Configuration
#   --------------------------------

#     This file is made up of the defaults for new configurations. It will not
#     be overwritten when running dotfiles/install.rb. However if it doesn't
#     exist, then it will be created in this initial state.


### Included Files, Directories & Other Settings

included: .config .fonts.conf .gvimrc .pryrc .tmux.conf .vim .vimrc .zshrc .wmii .xinitrc .Xresources

other-settings:
  arch-linux: yes
  gnome-terminal: yes
  sublime-text: yes


### X Terminal

colourscheme: foolish_passion_bright    # Colourschemes are found in dotfiles/.xcolourschemes.


### Fonts

font: ubuntu mono
font-size: 13.5
font-antialias: yes
font-hinting: no
font-hinting-style: none    # eg. hintnone, hintslight, hintmedium, hintfull


### wmii

colourscheme: wmii_foolish_passion    # Colourschemes are found in dotfiles/.xcolourschemes.
background-image: none    # Requires that feh is installed. Specify a full pathname.
