#!/bin/bash

echo "Copying all dotfiles to home directory."
cp -r .config .fonts.conf .gvimrc .vim .vimrc .zshrc $HOME/

if [ -d $HOME/.config/sublime-text-2 ]; then
  echo "Copying Sublime Text 2 configuration."
  echo "Remember to remove 'Vintage' from ignored packages."
  cp .sublime/* $HOME/.config/sublime-text-2/Packages/User/
fi
