class Dotfile

  class Static

    attr_reader :name, :source, :destination, :destination_path

    # The dotfile hash is generated by Dotfile::GroupConfig
    def initialize(dotfile_hash)
      @source = dotfile_hash[:source]
      @destination = dotfile_hash[:destination]
      @destination_path = File.dirname(@destination)
    end

    def name
      File.split(@source).last
    end

  end

end
