
#   Kelsey's Dotfile Configuration
#   --------------------------------

#     This file is made up of the defaults for new configurations. It will not
#     be overwritten when running dotfiles/install.rb. However if it doesn't
#     exist, then it will be created in this initial state.


### Included Files, Directories

included-groups: zsh vim tmux xorg wmii ruby dwb midori dircolors


### Other Settings (shell scripts in ./lib/optional)

optional-before:

optional-after:
  arch-linux: false
  cygwin: false
  gnome-terminal: false
  mintty: false
  sublime-text: false
  xrdb-reload: false


### X Terminal

x-theme: foolish_passion    # Themes are found in resources/themes.

urxvt-fading: 75
urxvt-scrollbar: false
urxvt-size: 134x34


### ZSH

zsh-prompt: default
zsh-tmux-auto: off
zsh-editor: vim
zsh-mode: v # eg. 'v' for Vi, 'e' for Emacs


### VIM

vim-syntax: "on"
vim-colourscheme: molokai

gvim-colourscheme: freckle
gvim-columns: 130
gvim-lines: 40


### Fonts

font: ubuntu mono
font-style: medium
font-size: 13.5
font-dpi: 96

font-antialias: true
font-autohint: true
font-hinting: true
font-hinting-style: hintnone    # eg. hintnone, hintslight, hintmedium, hintfull
font-rgba: none    # eg. none for grayscale anti-alias

urxvt-linespace: 3


### Tmux

# Eventually I'd like these to be generated by Chromatic.
# Set a default (something like below), but allow Chromatic themes to set
# certain colours per theme (as a theme may only want to change the default
# active window colour or something).

tmux-mouse-interaction: "on"
tmux-windowlist-alignment: left
tmux-show-activity: "on"

tmux-pane-fg: white
tmux-pane-bg: black

tmux-active-pane-fg: magenta
tmux-active-pane-bg: black

tmux-status-bg: black
tmux-status-fg: white
tmux-status-attr: dim

tmux-window-fg: white
tmux-window-bg: black
tmux-window-attr: dim

tmux-active-window-fg: white
tmux-active-window-bg: red
tmux-active-window-attr: bright

tmux-message-fg: white
tmux-message-bg: black
tmux-message-attr: bright


### wmii

wmii-theme: wmii_foolish_passion    # Themes are found in dotfiles/templates/themes.
wmii-default-terminal: urxvt
wmii-background-enabled: "# "    # "# " to disable, "" to enable.
wmii-background-image: /path/to/background.jpg    # Requires that feh is installed. Specify a full pathname.
