module Dotfile

  class Static

    attr_reader :name, :group, :content
    attr_reader :source, :destination, :destination_path

    # The dotfile hash is generated by Dotfile::GroupConfig
    def initialize(dotfile)
      @group = dotfile[:group]
      @source = dotfile[:source]
      @destination = dotfile[:destination]
      @destination_path = File.dirname(@destination)

      @content = content
    end

    def filename
      File.split(@source).last
    end

    def name
      filename
    end

    def content
      File.readlines(@source)
    end

  end

end
