require 'fileutils'

module Dotfile

  class Base

    include FileUtils

    attr_reader :name, :group, :content
    attr_reader :source, :destination, :destination_path

    # dotfile generated by Dotfile::GroupConfig
    def initialize(dotfile)
      @group = dotfile[:group]
      @source = dotfile[:source]
      @destination = dotfile[:destination]
      @destination_path = File.dirname(@destination)
    end

    def filename
      File.split(@source).last
    end

    def name
      filename
    end

    def update
      mkdir_p(@destination_path)
      File.write(@destination, @content.join)
    end

  end

end
